global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus-source"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node-source"
    static_configs:
    - targets: ["node-exporter:9100"]

remote_write:
  - url: "http://prometheus-sink:9090/api/v1/write"
    # basic_auth:
    #   username: "<Your Grafana Username>"
    #   password: "<Your Grafana API key>"