[api]
enabled = true
address = "0.0.0.0:8686"

[sources.demo_logs]
type = "demo_logs"
interval = 1.0
format = "json"

[sinks.console]
inputs = ["demo_logs"]
target = "stdout"
type = "console"
encoding.codec = "json"

[sources.my_source_id]
type = "prometheus_remote_write"
address = "0.0.0.0:9090"
auth.username="username"
auth.password="password"

[sink.prometheus_sink]
type = "prometheus_remote_write"
address = "0.0.0.0:9090"
auth.username="username"
auth.password="password"
